[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sbi4atmret"
version = "0.1.0"
description = "Simulation-Based Inference for Atmospheric Retrieval"
authors = [{name = "Malavika Vasist"}]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "tqdm",
    "torch>=2.0",
    "wandb",
    "pydantic>=2.0",
    "scipy",
    "h5py",
]

[project.optional-dependencies]
docs = [
    "sphinx>=7.0",
    "furo",
    "sphinx-autodoc-typehints",
    "myst-parser",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sbi4atmret*"]
